/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103Cx6.h"
#include "STM32F103C6_GPIO_Driver.h"
#include "../HAL/Includes/LCD.h"
#include "../HAL/Includes/Keypad.h"
#include "STM32F103C6_EXTI_Driver.h"
#define ZERO 0x01
#define ONE 0x79
#define TWO 0x24
#define THREE 0x30
#define FOUR 0x4C
#define FIVE 0x12
#define SIX 0x02
#define SEVEN 0x19
#define EIGHT 0x00
#define NINE 0x10
void clock_init()
{
	//Enable clock GPIO
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}

void GPIO_init()
{
	GPIO_PinConfig_t PinCfg;
	PinCfg.GPIO_PinNumber = GPIO_PIN_9;
	PinCfg.GPIO_MODE	  = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_Speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);
	PinCfg.GPIO_PinNumber = GPIO_PIN_10;
	PinCfg.GPIO_MODE	  = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_Speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);
	PinCfg.GPIO_PinNumber = GPIO_PIN_11;
	PinCfg.GPIO_MODE	  = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_Speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);
	PinCfg.GPIO_PinNumber = GPIO_PIN_12;
	PinCfg.GPIO_MODE	  = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_Speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_MODE	  = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_Speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);
	PinCfg.GPIO_PinNumber = GPIO_PIN_14;
	PinCfg.GPIO_MODE	  = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_Speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);
	PinCfg.GPIO_PinNumber = GPIO_PIN_15;
	PinCfg.GPIO_MODE	  = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_Speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);
}

int main (void)
{
	EXTI_PinConfig_t EXTI_CHG;
	EXTI_CHG.EXIT_PIN = EXTI0_GPIOA0;
	clock_init();
	LCD_INIT();
	Keypad_init();
	GPIO_init();
	unsigned char key_pressed;
	LCD_WRITE_STRING("HEY");
	my_wait(15);
	LCD_clear_screen();
	unsigned char LCD_display[11] = {'0','1','2','3','4','5','6','7','8','9','0'};
	unsigned char SEVEN_SEG_display[11] = {ZERO,ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE,ZERO};
	unsigned char i = 0;
	for(i=0;i<11;i++)
	{
		LCD_WRITE_CHAR(LCD_display[i]);
		MCAL_GPIO_WritePort(GPIOB, SEVEN_SEG_display[i]<<9);
		my_wait(100);
	}
	LCD_clear_screen();
	Keypad_init();
	LCD_WRITE_STRING("Keypad is ready");
	my_wait(30);
	LCD_clear_screen();
	while (1)
	{
		key_pressed = Keypad_getkey();
		switch (key_pressed) {
		case 'A':
			break;
		case '?':
			LCD_clear_screen();
			break;
		default:
			LCD_WRITE_CHAR(key_pressed);
			break;
		}
		//			if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1)== 0)
		//			{
		//				MCAL_GPIO_TogglePin(GPIOA, GPIO_PIN_1);
		//				while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1)== 0);
		//			}
		//			if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13)== 1)
		//			{
		//				MCAL_GPIO_TogglePin(GPIOA, GPIO_PIN_13);
		//			}
		my_wait(1);
	}
}



